### ISSUE TITLE
Create a NuGet Package

### ISSUE THREAD

**Issue by difrnt** [lolp1/Overlay.NET#1]
Might want to create a NuGet package to help satisfy the lazy/efficient developer. 😄

**Comment by lolp1** [comment]
I love how you called it both lazy and efficient in the same sentence! I understand the desire for a NuGet package, however I am currently working on finishing unit test, and support for detouring directx. At that point I shall start publishing the NuGet package when I commit to the main branch.

Hope to have it going in the next couple of weeks :)

**Comment by lolp1** [comment]
https://www.nuget.org/packages/Overlay.NET/

Please report issues. I am new to NuGet but if you want to use D3D functionality you might need to add the following packages in addition to the Overlay.NET package to use D3D overlay (not sure..).

SharpDX
SharpDXDirect2D1
SharpDXDXGI
Process.NET

**Comment by lolp1** [comment]
Closing for now.
