### ISSUE TITLE
Directx text is a little blurred?

### ISSUE THREAD

**Issue by xNarkon** [lolp1/Overlay.NET#10]
Hello I found a little problem, text in overlay using Directx is a little blurred, is there any way to fix it?

`_font = OverlayWindow.Graphics.CreateFont("Verdana", 10, true);
OverlayWindow.Graphics.DrawText("Text", _font, OverlayWindow.Graphics.CreateBrush(Color.White), 10, 60);

Screen:
http://screenshot.sh/odAszhlgOyu7f

On every font size it's just a little blurred even with Arial, Tahoma etc fonts. the problem must be somewhere else.
`

**Comment by lolp1** [comment]
I am unsure of a way to fix this issue and have no way to reproduce it and do not intend to fix it personally, sorry about that. If anyone decides to figure it out or you do make a pull request please :-)
