### ISSUE TITLE
Overlay in fullscreen apps

### ISSUE THREAD

**Issue by YSXrus** [lolp1/Overlay.NET#11]
Is it possible to draw overlay in fullscreen games? I've looked at the demo, and seems like it can't.

**Comment by lolp1** [comment]
For external overlays, rendering over a full screen application is simply not possible in any circumstance. This is sadly not even a limitation of this library, it is a limitation to any external overlay. 

I have internal overlay support but I am considering how much of that to implement into this library currently. I am considering doing a small license fee version of this lib with much more user friendly support and internal rendering (which would allow full screen).

**Comment by lufthavn** [comment]
We're in a situation where we're gonna need this functionality soon. If you can provide a version of this lib with easy-to-use internal rendering and user support, we would gladly pay for it. 😄

**Comment by inorton** [comment]
I had just found I wanted this, but luckily Elite:Dangerous has a Borderless-window full-screen mode which works fine

**Comment by lolp1** [comment]
@lufthavn Small update.. roughly three weeks out from version I intend to do on a license system -- that supports D3D9/D3D11for both x86 and x64 with a single base class. While it provides the user accsess to render content directly in EndScene/Present via their own d3d code, it also will have some basic wrappers for standard shapes/text/filing of shapes built in that will take no d3d experience.

**Comment by lufthavn** [comment]
@lolp1 That sounds awesome, when you feel you're ready, feel free to contact me at tobiaskastrupandersen@gmail.com, and we can chat about how to do this. 😄 
I'll be very busy the coming weeks, so please bear with me if I don't respond right away. 😄

**Comment by lolp1** [comment]
@xaviermonin @inorton @lufthavn  Working on it again now. Will update soon.
