### ISSUE TITLE
Bad Brushes

### ISSUE THREAD

**Issue by CorrM** [lolp1/Overlay.NET#20]
i just cant create brush for all colors expect the MAIN COLORS
like red blue green yellow
try this
`int Brush = OverlayWindow.Graphics.CreateBrush(0xFFD700);`

it's gold color will not work

**Comment by lolp1** [comment]
> 
> 
> i just cant create brush for all colors expect the MAIN COLORS
> like red blue green yellow
> try this
> `int Brush = OverlayWindow.Graphics.CreateBrush(0xFFD700);`
> 
> it's gold color will not work

That is not an issue with the library. You must create the color correctly. 
```csharp
var brush = OverlayWindow.Graphics.CreateBrush(System.Drawing.ColorTranslator.FromHtml("#FFFFFF"));
```
