### ISSUE TITLE
DirectX not drawing on my computers

### ISSUE THREAD

**Issue by thgiang** [lolp1/Overlay.NET#22]
I read some other issue but author closed it. The issue still occurs on my computer Window 7
I tried to use Overlay.NET.Demo and WPF work but DirectX overlay not show anything.

My computer is: 
![image](https://user-images.githubusercontent.com/9299251/49877810-1f282a00-fe1e-11e8-8ffb-4131b8491e15.png)

DirectX 11 - NVDIA GeForce GTX 960

**Comment by CorrM** [comment]
i think u must start with that
https://www.technorms.com/5094/windows-7-aero

**Comment by thgiang** [comment]
Ok I find out. Problem is Win 7 disable Transparent key. Copy this text and save to abc.reg file. Run it.

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM]
"ColorizationOpaqueBlend"=dword:00000000

**Comment by lolp1** [comment]
> 
> 
> Ok I find out. Problem is Win 7 disable Transparent key. Copy this text and save to abc.reg file. Run it.
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM]
> "ColorizationOpaqueBlend"=dword:00000000

Perhaps if I detect windows 7, I can make a big bold message box pop up asking if they want to disable that in order for it to work and offer a popup to re-enable it.
