### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jaku** [lolp1/Overlay.NET#29]
Could you add a license to this project?

**Comment by lolp1** [comment]
@jaku I intended to monetize it one day through a 6 month license model with provided support etc. Not sure if/when I ever will, but that is why I did not insert a license. If you want to use this version or something made from this version on your own, for free in something for-profit, I am glad to issue a single-use license suited to you for that purpose directly. Just reply how to contact you if thats your desire.

**Comment by jaku** [comment]
Sure, please contact me at at jaku@warp.world.
