### ISSUE TITLE
The handle of the parent window isn't valid

### ISSUE THREAD

**Issue by HelloKitty** [lolp1/Overlay.NET#31]
Demo code works fine when run in a console application but when I try to copy the demo code into another application, specifically Unity3D for testing, it fails to create the overlay on the target process which is another DirectX application.

However it doesn't make sense why this would occur as there is no other error and the process name provided is identitical to what is used in the Demo.

**Comment by HelloKitty** [comment]
Possiblity a Unity3D/Mono issue. MainWindowHandles seem to always be 0 https://www.reddit.com/r/Unity3D/comments/6zrin4/processmainwindowhandle_is_always_0/

**Comment by HelloKitty** [comment]
Forking Process.NET and managing MainWindowHandle manaully solved the issue.

**Comment by lolp1** [comment]
> Forking Process.NET and managing MainWindowHandle manaully solved the issue.

Glad to hear!
