### ISSUE TITLE
In Full screen mode of game not working

### ISSUE THREAD

**Issue by softinfytechnology** [lolp1/Overlay.NET#37]
Hello Dev,
It is really nice example!

But when game is going into Full screen mode then not working the overlay screen.
So basically it should work in Game Full screen mode as well right?

Anyone has any comment on this please?

**Comment by XeCrash** [comment]
I am not entirely certain if this is right to don't quote me but, this library uses internal commands but does the hooking externally, you'd probably have to build a shared library .dll that you'd inject into target game process to be able to support something like this. Guided Hacks has a good tutorial on making internal cheats that use directX and carious other graphic API's to achieve fullscreen rendering. That is all coded in C++ so its a good idea to brush up on it

**Comment by lolp1** [comment]
> Hello Dev, It is really nice example!
> 
> But when game is going into Full screen mode then not working the overlay screen. So basically it should work in Game Full screen mode as well right?
> 
> Anyone has any comment on this please?

Unfortuanly that is correct this will not work in full screen and there is no solution for that using this rendering method. You will need to obtain the directx device directly usually via hook and tap right into the direct rendering resource to achieve full screen rendering.
