### ISSUE TITLE
Overlay not drawing in fullscreen mode

### ISSUE THREAD

**Issue by abratar** [lolp1/Overlay.NET#6]
So the game im using is csgo and im using the directx version and everything works fine in windowed mode. smooth af. but when i switch to fullscreen nothing is showing. if i switch back to windows then it draws again... what can the problem be here? or is the only way to play the game in fullscreen windowed? i hope i get an answer if this project is still alive :D

**Comment by lolp1** [comment]
There is no way to use this overlay in true fullscreen mode as far as I know. If some one knows a way to get that to work I will implement it. To be honest I can not think of a single reason to run anything but full screen windowed.

**Comment by abratar** [comment]
hmm, i guess the only thing would be to use the game's directx. thanks anyways

**Comment by lolp1** [comment]
Can you explain why you need to use full screen versus window full screen? What benefits does it provide over windowed full screen?

**Comment by abratar** [comment]
for me its just the color and the framerate is different. in windowed fullscreen it uses my windows color settings and in fullscreen it uses my ingame + screen color settings.

**Comment by Traderain** [comment]
Also the thing you have to understand is we are making something for users and you have to be prepared for every usecase. So for example not supporting fullscreen may make someone's 10% of costumer base unhappy.

**Comment by lolp1** [comment]
@Traderain I think it is pretty clear in a for-profit business situation, something like no support for full-screen could make some customers unhappy. 

This is however, is a free project supported on my spare time. In my ideal world I would love to support full-screen and make everyone happy. Sadly, I have to prioritize what I can do in this project. As far as I can tell, on modern computers which is what this project aims at supporting, 'true' full screen offers very little more, and often, none or even less benefit over borderless or 'windowed full screen' modes.

For this reason, I am closing this issue. No full screen will be able to be supported until in-process is added.
