### ISSUE TITLE
Redrawing the WPF overlay

### ISSUE THREAD

**Issue by mattukdev** [lolp1/Overlay.NET#8]
I am trying to create an overlay using WPF and a simple bitmap image. I am able to draw the bitmap image and have done so by using the examples in both the Draw event and the SetUp(); function.

However, I want to be able to update this image and redraw it on the overlay.

I have tried to execute SetUp(); with a new image but cannot seem to get rid of the old image. I have tried using the OverlayWindow.Remove(); but that doesn't seem to work either. I have tried removing the condition so SetUp(); is triggered every PreTick but that doesn't seem to work either.

Draw seems to only be triggered upon the initial draw but never again.

How can I redraw the overlay with a new image?

Here is my current SetUp();

[OverlayWPF2.txt](https://github.com/lolp1/Overlay.NET/files/787296/OverlayWPF2.txt)

Thanks for all your hard work on this @lolp1 , it works very well.

**Comment by lolp1** [comment]
Have you tried just storing a reference to the Rectangle and changing the 'Fill' with the new value? You may also try actually removing the item from the Children property in the overlay window and adding the new one on a new frame. Inefficient but should work.

**Comment by larsbloch** [comment]
I have the same issue. The overlay.Update is called many times, but the redraw function is only called once (or actually a couple of times) in the beginning.
I tried changing "click me" to datetime.now.seconds.tostring() but it just stays the same.

**Comment by lolp1** [comment]
Fixing this soon as well as the ability to get events.
