### ISSUE TITLE
Some kind of tutorials required

### ISSUE THREAD

**Issue by ArtyomIsFlash** [lolp1/Overlay.NET#9]
Demo isn't that easy to understand, so... and tutorials? Because wiki doesn't work

**Comment by Traderain** [comment]
http://stylesoftware.net/Overlay.NET/Overlay.NET.Demo.mp4

**Comment by lolp1** [comment]
The demo is really as simple as you can get. It is a basic, working, compilable implementation of using both WPF and DirectX overlay plugins.

Can you specify what is confusing about it?

**Comment by ArtyomIsFlash** [comment]
It's about WPF only. I want to create an overlay for Need for Speed: Most Wanted 2005 using NFSScript and Overlay.NET
